[package]
name = "file-dialog"
version = "0.1.0"
authors = ["Charles Samborski <demurgos@demurgos.net>"]

[dependencies]
libc = "^0.2.33"
gtk = "^0.3.0"
gtk-sys = "^0.5.0"
qt_core = "^0.2.3"
qt_widgets = "^0.2.3"
